# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# chm2_generator.py
# Created on: 2019-02-19 12:13:53.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

arcpy.env.overwriteOutput = True

arcpy.CheckOutExtension("Spatial")

arcpy.env.workspace = sys.argv[1]

# Local variables:
bg_class_tif = "scratch/bg_class.tif"
chm_tif = "products/chm.tif"
con1_tif = "scratch/con1.tif"
Input_true_raster_or_constant_value = "0.015"
con2_tif = "scratch/con2.tif"
null_tif = "scratch/null.tif"
out_tif = "scratch/chm2.tif"

# Process: Con
arcpy.gp.Con_sa(bg_class_tif, chm_tif, con1_tif, "", "VALUE = 1")

# Process: Con (2)
arcpy.gp.Con_sa(con1_tif, Input_true_raster_or_constant_value, con2_tif, con1_tif, "VALUE > 0.015")

# Process: Is Null
arcpy.gp.IsNull_sa(con2_tif, null_tif)

# Process: Con (3)
arcpy.gp.Con_sa(null_tif, chm_tif, out_tif, con2_tif, "VALUE = 1 ")

arcpy.Delete_management(con1_tif)
arcpy.Delete_management(con2_tif)
arcpy.Delete_management(null_tif)

